server:
  port: 8080

app:
  base-url: http://localhost:8080

spring:
  application:
    name: shorty
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/shorty}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations:
      - db/migration
    baseline-on-migrate: true

jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400 # 24 hours in seconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.shorty: INFO
    org.springframework.security: DEBUG
